export const listProduct = [
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớttttttttttttttttttttttttttttttttttttttttttttttttttttttt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    },
    {
        _id:"1",
        typeId:1,
        name:"Gà nướng muối ớt",
        imageUrl:"https://cdn.huongnghiepaau.com/wp-content/uploads/2017/10/ga-nuong-muoi-ot.jpg",
        discountOff:10,
        description:"Cách làm gà nướng muối ớt là công thức được rất nhiều người săn lùng với mong muốn có thể tự chuẩn bị bữa tiệc cuối tuần chiêu đãi bạn bè, người thân. Bài viết giới thiệu cách làm món gà nướng ngon mê ly khiến người ăn xuýt xoa tán thưởng.",
        discountMaximum:20,
        createAt:"12-12-2020",
        price:2000000,
    }
]